import type { AdapterManifest } from "../../../packages/adapter-sdk/src/types";

export const openAiDocsManifest: AdapterManifest = {
  id: "openai.docs.page-extractors",
  version: "1.0.0",
  publisher: "adaptab",
  visibility: "public",
  execution: "page",
  product: "OpenAI documentation page extractors",
  origins: ["https://developers.openai.com", "https://learn.chatgpt.com"],
  pathPatterns: ["/*"],
  intentPatterns: [
    "code example",
    "code examples",
    "extract code",
    "example extractor",
    "api schema",
    "api parameters",
    "parameter schema",
    "read parameters",
  ],
  networkAllowlist: [],
  executionPolicy: {
    tabStrategy: "reuse_resolved_top_level_tab",
    additionalTabsRequired: false,
    resourceUrls: "navigation_targets",
    profileResolution: "page_navigation",
    requestConcurrency: "not_applicable",
  },
  agentGuidance: "Reuse the resolved OpenAI documentation top-level tab. Prefer the site's native search and navigation tools to open the relevant page, then use these namespaced AdapTab tools to extract bounded code examples or API parameters from that live document. Do not shadow the site's native tools or open an additional tab.",
  limits: [
    {
      id: "code-example-count",
      scope: "input",
      toolName: "adaptab_openai_docs_extract_code_examples",
      inputProperty: "limit",
      value: 10,
      reason: "reliability",
      source: "This reviewed DOM extractor is fixture-tested with at most ten normalized code blocks per invocation.",
      configurable: true,
      description: "The caller may extract at most ten code examples from the currently open documentation page.",
    },
    {
      id: "code-example-character-budget",
      scope: "output",
      value: 12000,
      reason: "reliability",
      source: "This adapter bounds each extracted DOM code block before returning it through WebMCP.",
      configurable: false,
      description: "Each returned code example is truncated to twelve thousand characters to bound the WebMCP result.",
    },
    {
      id: "api-parameter-count",
      scope: "input",
      toolName: "adaptab_openai_docs_read_api_schema",
      inputProperty: "limit",
      value: 50,
      reason: "reliability",
      source: "This reviewed DOM extractor is fixture-tested with at most fifty normalized API parameters per invocation.",
      configurable: true,
      description: "The caller may extract at most fifty API parameters from the currently open reference page.",
    },
    {
      id: "api-parameter-text-budget",
      scope: "output",
      value: 1200,
      reason: "reliability",
      source: "The adapter normalizes and bounds every declaration, type, and description read from the current page.",
      configurable: false,
      description: "Each returned API parameter contains bounded names, declarations, types, descriptions, constraints, and links.",
    },
  ],
  tools: [
    {
      name: "adaptab_openai_docs_extract_code_examples",
      description: "Extract bounded code examples from the currently open OpenAI documentation page through a third-party AdapTab adapter. Filter by language or text without replacing the site's native search and navigation tools.",
      routeFamily: "openai-documentation",
      readOnly: true,
      requiresConfirmation: false,
      inputSchema: {
        type: "object",
        properties: {
          language: {
            type: "string",
            minLength: 1,
            maxLength: 40,
            description: "Optional language label, such as TypeScript, Python, curl, HTTP, or JSON.",
          },
          contains: {
            type: "string",
            minLength: 1,
            maxLength: 120,
            description: "Optional case-insensitive text to match in code or its section heading.",
          },
          limit: {
            type: "integer",
            minimum: 1,
            maximum: 10,
            default: 5,
            description: "Maximum examples to return from the live page.",
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: "adaptab_openai_docs_read_api_schema",
      description: "Read a bounded, structured API parameter schema from the currently open OpenAI API reference page through a third-party AdapTab adapter. Uses semantic reference markup with a table fallback.",
      routeFamily: "openai-api-reference",
      readOnly: true,
      requiresConfirmation: false,
      inputSchema: {
        type: "object",
        properties: {
          query: {
            type: "string",
            minLength: 1,
            maxLength: 120,
            description: "Optional case-insensitive filter over parameter name, type, declaration, and description.",
          },
          language: {
            type: "string",
            minLength: 1,
            maxLength: 40,
            description: "Optional API reference language, such as HTTP, Python, TypeScript, Java, or Go.",
          },
          includeNested: {
            type: "boolean",
            default: false,
            description: "Include nested object properties as well as top-level request parameters.",
          },
          limit: {
            type: "integer",
            minimum: 1,
            maximum: 50,
            default: 20,
            description: "Maximum parameters to return from the live page.",
          },
        },
        additionalProperties: false,
      },
    },
  ],
};
